### PR TITLE
event handlers: tweak logging

### PR DESCRIPTION
**Pull request by williballenthin**
changes:
  - reduce verbosity of handle reloc log messages
  - uses logging instead of print for warning about deprecation

### CODE REVIEW

**Comment by rakuy0** [comment]
@williballenthin go ahead and merge whenever you're ready.

**Comment by williballenthin** [comment]
I don't have merge privs :-)

**Comment by rakuy0** [comment]
Whoops. Sorry. Forgot about that :P

**Comment by williballenthin** [comment]
thanks!

**Pull request merged**
