### PR TITLE
fix #149: enable envi.memory to parse opcodes from last 15 bytes of s…

### LINKED ISSUE #149: envi.memory.parseOpcode cannot decode instructions in last 15 bytes of section
`envi.memory.IMemory.parseOpcode()` cannot decode instructions in the last 15 bytes of a memory map because it blindly asks for 16 bytes from which to decode instructions. see here: https://github.com/vivisect/vivisect/blob/master/envi/memory.py#L301

this always fails in the last 15 bytes because `.readMemory()` calls `.probeMemory()` on 16 bytes, and because at least one byte overruns the section, the entire return buffer is taint data ("AAAAAAA...").

a potential fix is to take 16 bytes, unless we're at the end of the section, and then fetch data only to the end of the section.

### PR DESCRIPTION
**Pull request by williballenthin**
…ection

implements the potential fix described in #149. take 16 bytes from which to parse opcodes, when possible. otherwise, fetch as many bytes as we can, up to the end of a section.

### CODE REVIEW

**Comment by williballenthin** [comment]
@invisig0th would you please consider merging this patch?

**Comment by atlas0fd00m** [comment]
@williballenthin please look at PR 177 and see if this does what you want:

https://github.com/vivisect/vivisect/pull/177/files

i believe that will fix this and other problems.

cc: @invisig0th

**Comment by williballenthin** [comment]
oh, nice, thanks @atlas0fd00m

**Comment by atlas0fd00m** [comment]
:)  thanks.  please check out that branch, if you don't mind, and make sure it does indeed fix what you're after.  if not, i'll tweak it to make sure it does.

**Comment by mr-tz** [comment]
Yes, #177 fixes it. Thanks!

**Comment by atlas0fd00m** [comment]
awesome.  so glad.
@invisig0th the ball's in your court, my friend.

**Comment by williballenthin** [comment]
please prefer #177 to this patch

**Pull request closed without merging**
