### PR TITLE
elf: reduce logging verbosity for status messages

### PR DESCRIPTION
**Pull request by williballenthin**
reducing the logging level for "normal" messages during ELF parsing routines. i'd recommend that debug be used for expected, verbose messages, info be used for things a human really needs to know, and warning for errors that are handled without crashing the program. therefore, the fact that an ELF parsing routine is invoked or that a data structure is not found (but this is expected) should all be at the debug level.

as always, open to discussion.

### CODE REVIEW

**Comment by atlas0fd00m** [comment]
my approach, since default log levels are typically set to WARNING:
* INFO messages are the first level of important messages that someone *who is looking for more detail*  gets, and is basically following program structure (not nitty-gritty details
* DEBUG messages are more details for troubleshooting
* MIRE (we created this level) messages are to support low level debugging where determining "causality" without a debugger or manipulating code is the goal.

**Comment by atlas0fd00m** [comment]
thanks @williballenthin .  we don't turn down requests from you and your team without significant consideration.
in this case, we're going to keep the logging as is. 
closing this now, but i'm personally interested in your usage paradigm for the logging levels.

**Comment by williballenthin** [comment]
of course, no problem!

my lightweight guidelines are something like:

  - debug be used for expected, verbose messages ("I'm parsing this thing now"), 
  - info be used for things a human really needs to know ("the version used to do the work is v12"),  
  - warning for errors that are handled without crashing the program ("bad data encountered, rolling back"), and
  - error for errors that aren't handled well and probably end normal execution ("you have to provide a command line argument")

but they're hand-wavy and hard to specify perfectly. its understandable that not all projects adhere to these guidelines so fortunate that `logging` enables client applications to tune how messages from libraries are emitted.

**Comment by atlas0fd00m** [comment]
thanks @williballenthin!  i appreciate your thoughts.  i agree.  it's tough to match different projects exactly.

**Pull request closed without merging**
