### PR TITLE
import emulator to handle dynamic branches (switchcases) using only xrefs

### PR DESCRIPTION
**Pull request by atlas0fd00m**
this is helpful for manual xref additions as well as switchcases where the instruction doesn't flag as BR_TABLE.

### CODE REVIEW

**Review by rakuy0 — CHANGES_REQUESTED** [review]
Do you have any binary on hand that this fixes the emulation for? Because I'd love to get some unit tests for this in.

**Comment by atlas0fd00m** [comment]
currently, until symbolik switchcase is merged in (where these xrefs get added in a non-manual fashion), this situation only happens manually.  we can manually add some code xrefs and emulate through to test it.  is that sufficient?

**Comment by rakuy0** [comment]
Eh, don't worry about it. Just add a TODO on that section of code and we can add tests for it once symbolik switchcase is merged in.

**Review by rakuy0 — APPROVED** [review]

**Comment by atlas0fd00m** [comment]
will do.  working on a few unittests already for switchcases, this will help.

**Pull request merged**
